const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function page(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));scrollTo(0,0)}
$$('[data-page]').forEach(b=>b.onclick=e=>{e.preventDefault();page(b.dataset.page)});
const words=[['Resilient','/rɪˈzɪliənt/','Able to recover quickly from difficulty or change.','She remained resilient after facing several challenges.',['strong','adaptable','tough']],['Curious','/ˈkjʊəriəs/','Eager to learn, know, or discover something.','A curious student asks useful questions.',['inquisitive','interested','eager']],['Diligent','/ˈdɪlɪdʒənt/','Showing careful and persistent effort.','He is diligent about daily practice.',['hardworking','careful','dedicated']],['Confident','/ˈkɒnfɪdənt/','Feeling sure about your abilities.','She became confident after practice.',['assured','bold','certain']]];let wi=0;
function word(){let w=words[wi%words.length];$('#word').textContent=w[0];$('#pron').textContent=w[1];$('#meaning').textContent=w[2];$('#example').textContent=w[3];$('#count').textContent=`${wi%100+1} / 100`;$('#syn').innerHTML=w[4].map(x=>`<span>${x}</span>`).join('')}
$('#newWord').onclick=()=>{wi++;word()};word();
const qs=[['What does resilient mean?',['Able to recover from difficulty','Unable to change','Very expensive','Very quiet'],0],['Choose the correct sentence.',['She go to college.','She goes to college.','She going college.','She gone college.'],1],['Which word means eager to learn?',['Curious','Brief','Ancient','Silent'],0],['Choose the past tense.',['I study yesterday.','I studied yesterday.','I studying yesterday.','I studies yesterday.'],1],['Which word means clear and brief?',['Long','Concise','Difficult','Ancient'],1]];let qi=0,sc=0,done=false;
function quiz(){let q=qs[qi];done=false;$('#qnum').textContent=`Question ${qi+1} of ${qs.length}`;$('#question').textContent=q[0];$('#feedback').textContent='';$('#next').hidden=true;$('#answers').innerHTML=q[1].map((a,i)=>`<button class="answer" data-i="${i}">${a}</button>`).join('');$$('.answer').forEach(b=>b.onclick=()=>answer(+b.dataset.i))}
function answer(i){if(done)return;done=true;let q=qs[qi];$$('.answer').forEach((b,n)=>{if(n===q[2])b.classList.add('correct');if(n===i&&i!==q[2])b.classList.add('wrong')});if(i===q[2]){$('#score').textContent=++sc;$('#feedback').textContent='Correct! 🎉'}else $('#feedback').textContent='Good attempt. Try again!';$('#next').hidden=false}
$('#next').onclick=()=>{qi++;if(qi>=qs.length){$('#question').textContent=`Quiz complete! Score ${sc}/${qs.length}`;$('#answers').innerHTML='';$('#next').hidden=true;setTimeout(()=>{qi=0;sc=0;$('#score').textContent=0;quiz()},1800)}else quiz()};quiz();
$('#listen').onclick=()=>{if('speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance($('#target').textContent);u.lang='en-US';u.rate=.9;speechSynthesis.speak(u)}};
$('#check').onclick=()=>{let a=$('#target').textContent.toLowerCase().replace(/[.,!?]/g,'').split(/\s+/),b=$('#spoken').value.toLowerCase().replace(/[.,!?]/g,'').split(/\s+/);if(!b[0])return $('#sresult').textContent='Please type what you said first.';let m=a.filter(x=>b.includes(x)).length,s=Math.round(m/a.length*100);$('#sresult').textContent=`Your practice score: ${s}/100. ${s>=80?'Excellent! 🌟':'Good attempt. Speak slowly and clearly.'}`};
$('#api').onclick=()=>$('#modal').classList.add('show');$('#close').onclick=()=>$('#modal').classList.remove('show');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('show')};
$('#save').onclick=()=>{let k=$('#key').value.trim();k?localStorage.setItem('lumina_gemini_key',k):localStorage.removeItem('lumina_gemini_key');$('#status').textContent=k?'Saved on this device.':'Key removed.'};
